[package]
name = "snarkos-node-metrics"
version = "2.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A node for a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "GPL-3.0"
edition = "2021"

[dependencies.metrics]
version = "0.20"

[dependencies.metrics-exporter-prometheus]
version = "0.11"

[dependencies.tokio]
version = "1.23"
features = ["rt"]
